import tkinter as tk 
window = tk.Tk () 
window.title('Frames') 
#window.geometry('600x800') 
window.columnconfigure(0, weight = 1) 
window.rowconfigure(0, weight = 1)
mainframe = tk.Frame(window, borderwidth = 5, relief = 'sunken' ) #groove, ridge, solid, sunken , raised
mainframe.grid(sticky = 'nsew', padx = 10, pady = 10) 
mainframe.columnconfigure(0, weight = 1)
mainframe.columnconfigure(1, weight = 1)
mainframe.rowconfigure(0, weight = 1)  
mainframe.rowconfigure(1, weight = 1)
#label1 = tk.Label(mainframe, text = 'I am a label', fg = 'blue', bg = 'red') 
#label1.grid(row = 0, column = 0) 
topframe = tk.Frame(mainframe, borderwidth = 3, relief = 'raised') 
topframe.grid(sticky = 'nsew', row = 0, column = 0, columnspan = 2, padx = 5, pady = 5)
label_2 = tk.Label(topframe, text = 'Topframe', fg = 'red', bg = 'blue')
label_2.grid(row = 0, column = 0) 
leftframe = tk.Frame(mainframe, borderwidth = 5, relief = 'groove') 
leftframe.grid(sticky = 'nsew', row = 1, column = 0, padx = 5, pady = 5) 
label_3 = tk.Label(leftframe, text = 'Leftframe', fg = 'white', bg = 'black') 
label_3.grid(row = 0, column = 0) 
rightframe = tk.Frame(mainframe, borderwidth = 5, relief = 'ridge', bg = 'black' ) 
rightframe.grid(sticky = 'nsew', row = 1, column = 1, padx = 5, pady = 5)
label_4 = tk.Label(rightframe, text = 'Rightframe', fg = 'white', bg = 'black') 
label_4.grid(row = 0, column = 0) 
window.mainloop()